### ISSUE TITLE
Naming Convention

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Volpe_Unity#5]
CS_Volpe_Unity? or maybe Volpe_Unity is a new CityScience City ;-)?

**Comment by agrignard** [comment]
to be totally coherent I would put CS. CSL is suppose to be clearly for the CityScience Network no?
And the CityScience@MediaLab even if it's a "deployement" is made by us so CS no? Like CS_Andorra_Table_Demo

**Comment by RELNO** [comment]
Sounds good!
